# Dockerfile for Nginx web server
FROM nginx:latest

# Set the working directory in the container
WORKDIR /usr/share/nginx/html

# Copy the current directory contents into the container at /usr/share/nginx/html
COPY . .

# Expose port 80 to the outside world
EXPOSE 80

# Command to run Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]

# run the container with:
# docker build -t my-nginx .
# docker run -d -p 80:80 my-nginx
# check the local server at http://localhost:80